# Generated by Django 3.0.8 on 2020-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Query - Messages'},
        ),
        migrations.AlterModelOptions(
            name='eventsgallery',
            options={'verbose_name_plural': 'Z: Do not open - Eventgallaries'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home - 1st'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Query - Subscribed'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name_plural': 'Home - 4th'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name_plural': 'Home - 3rd'},
        ),
        migrations.AlterModelOptions(
            name='whoarewe',
            options={'verbose_name_plural': 'Home - 2nd'},
        ),
        migrations.AlterModelOptions(
            name='whoareweimage',
            options={'verbose_name_plural': 'Z: Do not open - Whoareweimage'},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='saving_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='events',
            name='slogan',
            field=models.CharField(blank=True, default='Untitled', max_length=100, null=True),
        ),
    ]
