# Generated by Django 3.0.8 on 2020-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
