# Generated by Django 3.0.8 on 2020-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200809_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whatwedo',
        ),
        migrations.RemoveField(
            model_name='whoarewe',
            name='title',
        ),
        migrations.AddField(
            model_name='hometitles',
            name='home_third_section',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
