# Generated by Django 3.0.8 on 2020-08-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200809_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
    ]
