# Generated by Django 3.0.8 on 2020-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whoarewe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='whoarewe')),
            ],
        ),
    ]
