# Generated by Django 3.0.8 on 2020-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometitles',
            name='about_image_gallery',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='about_our_work',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='all_our_advisors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='all_our_partners',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='all_our_team',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='event_description_our_work',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='home_our_work',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='home_third_section',
            field=models.TextField(),
        ),
    ]
