# Generated by Django 3.0.8 on 2020-08-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200809_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometitles',
            old_name='event_description_our_work',
            new_name='events_our_work',
        ),
    ]
