# Generated by Django 3.0.8 on 2020-08-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200809_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometitles',
            name='about_our_work',
        ),
        migrations.RemoveField(
            model_name='hometitles',
            name='all_our_team',
        ),
        migrations.RemoveField(
            model_name='hometitles',
            name='events_our_work',
        ),
        migrations.RemoveField(
            model_name='hometitles',
            name='home_our_work',
        ),
        migrations.RemoveField(
            model_name='hometitles',
            name='home_third_section',
        ),
        migrations.AddField(
            model_name='hometitles',
            name='about_our_work_head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='about_our_work_span',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='all_our_team_head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='all_our_team_span',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='events_our_work_head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='events_our_work_span',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='home_our_work_head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='home_our_work_span',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='home_third_section_head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitles',
            name='home_third_section_span',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='about_image_gallery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='all_our_advisors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hometitles',
            name='all_our_partners',
            field=models.CharField(max_length=200),
        ),
    ]
