# Generated by Django 3.0.8 on 2020-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200804_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whoareweimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='whoarewe')),
            ],
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventsgallery',
            options={'verbose_name_plural': 'Eventgallaries'},
        ),
    ]
