# Generated by Django 3.0.8 on 2020-08-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200804_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
