# Generated by Django 3.0.8 on 2020-08-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_events_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name_plural': 'Values'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name_plural': 'Whatwedo'},
        ),
        migrations.AlterModelOptions(
            name='whoarewe',
            options={'verbose_name_plural': 'Whoarewe'},
        ),
        migrations.AlterModelOptions(
            name='whoareweimage',
            options={'verbose_name_plural': 'Whoareweimage'},
        ),
    ]
