# Generated by Django 3.0.8 on 2020-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200809_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='brief_info',
            field=models.CharField(max_length=150),
        ),
    ]
