# Generated by Django 3.0.8 on 2020-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
