# Generated by Django 3.0.8 on 2020-08-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200804_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoareweimage',
            name='events',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.Whoarewe'),
        ),
    ]
