# Generated by Django 3.0.8 on 2020-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_whoareweimage_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
