# Generated by Django 3.0.8 on 2020-08-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200809_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
