# Generated by Django 3.0.8 on 2020-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_home_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='values',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whoarewe',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
