# Generated by Django 3.0.8 on 2020-08-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_events_upcoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='upcoming',
        ),
    ]
