# Generated by Django 3.0.8 on 2020-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20200804_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='photo',
            new_name='photo_big',
        ),
        migrations.AddField(
            model_name='values',
            name='photo_small',
            field=models.ImageField(blank=True, null=True, upload_to='values'),
        ),
    ]
