# Generated by Django 3.0.8 on 2020-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_events_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
