# Generated by Django 3.0.8 on 2020-08-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_events_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='About')),
                ('data', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.About')),
            ],
            options={
                'verbose_name_plural': 'Z: Do not open - Eventgallaries',
            },
        ),
    ]
