# Generated by Django 3.0.8 on 2020-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_aboutgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body_left_image',
            field=models.ImageField(default=1, upload_to='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='body_right_image',
            field=models.ImageField(default=1, upload_to='about'),
            preserve_default=False,
        ),
    ]
