# Generated by Django 3.0.8 on 2020-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_advisors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisors',
            options={'verbose_name_plural': 'Advisors'},
        ),
        migrations.AddField(
            model_name='advisors',
            name='post',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
