# Generated by Django 3.0.8 on 2020-08-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20200809_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slogan',
            field=models.CharField(blank=True, default='Untitled', max_length=100, null=True),
        ),
    ]
