# Generated by Django 3.0.8 on 2020-08-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20200809_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinus',
            options={'verbose_name_plural': 'Query - JoinUs'},
        ),
        migrations.AlterField(
            model_name='joinus',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
