# Generated by Django 3.0.8 on 2020-08-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200810_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='cv',
            field=models.FileField(default=1, upload_to='cv'),
            preserve_default=False,
        ),
    ]
